echo ""
echo " _    _       _       _      _       "
echo "| | _(_)_ __ | | __ _| |__  (_) ___  "
echo "| |/ / | '_ \| |/ _' | '_ \ | |/ _ \ "
echo "|   <| | |_) | | (_| | |_) || | (_) |"
echo "|_|\_\_| .__/|_|\__,_|_.__(_)_|\___/ "
echo "       |_|                           "
echo "Moving satellites into position"
echo ""