version: '3.7'

services:
  vertxwmdb-service:
    image: mongo:latest
    container_name: vertxwmdb
    command: "mongod --smallfiles"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
      MONGO_INITDB_DATABASE: vertxwmdb
    ports:
      - 27017:27017
    volumes:
      - ../../mongo/db:/data/db
      - ../../mongo/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
